routes/web.php
<?php

use App\Post;
use App\Partner;

// use Symfony\Component\Debug\Debug;
// Debug::enable();

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/


/*
|--------------------------------------------------------------------------
| WORKING
|--------------------------------------------------------------------------
*/

Route::get('video-test', 'Admin\VideoController@index')->name('video-test.index');


/*
|--------------------------------------------------------------------------
| NEED UPDATE
|--------------------------------------------------------------------------
*/

// need to create a controller for these maybe Main or FrontendController
Route::get('/', function () {
    return view('new');
});

/*
|--------------------------------------------------------------------------
| DONE
|--------------------------------------------------------------------------
*/

// Auth
Auth::routes();
// Logout
Route::get('/logout', 'Auth\LoginController@logout');


/*
|
|
|--------------------------------------------------------------------------
| Admin Routes (Admin Panel)
|--------------------------------------------------------------------------
|
*/

// Admin Panel Routes
Route::prefix('admin')->group(function () {

  /*
  |--------------------------------------------------------------------------
  | WORKING
  |--------------------------------------------------------------------------
  | - add video library to manage all the video in once then assign to apps.
  */
  Route::prefix('/video-library')->group(function() {
    Route::resource('/video-api-library', 'Admin\VideoLibraryController');
    Route::get('/', function() {
      return view('admin.video_library.index');
    })->name('video-library.index');
  });

  /*
  |--------------------------------------------------------------------------
  | DONE
  |--------------------------------------------------------------------------
  */
  // Auth
  Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
  Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
  Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
  Route::get('/', 'AdminController@index')->name('admin');

  // Users menu routes
  Route::get('/admins', 'Admin\AdminController@index')->name('admin.admins.index');
  Route::resource('teachers', 'Admin\TeacherController', ['except' => ['create']]);
  Route::post('teachers/{teacher}', 'Admin\TeacherController@storeStudent')->name('teacher.store.student');
  Route::resource('students', 'Admin\StudentController', ['except' => ['create']]);
  Route::resource('users', 'Admin\UserController', ['except' => ['create']]);
  Route::resource('schools', 'Admin\SchoolController', ['except' => ['create']]);

  // Settings menu routes
  Route::resource('partners', 'Admin\PartnerController', ['except' => ['create'] ]);

});


/*
|
|
|--------------------------------------------------------------------------
| Teacher Routes (Teacher Panel)
|--------------------------------------------------------------------------
|
*/

// Teacher Panel Teacher
Route::prefix('teacher')->group(function() {
  // Auth
  Route::get('/login', 'Auth\TeacherLoginController@showLoginForm')->name('teacher.login');
  Route::post('/login', 'Auth\TeacherLoginController@login')->name('teacher.login.submit');
  Route::get('/logout', 'Auth\TeacherLoginController@logout')->name('teacher.logout');
  Route::get('/', 'TeacherController@index')->name('teacher');

  // Apps
  Route::get('/app', 'AppController@firstApp')->name('app.first');
});


/*
|
|
|--------------------------------------------------------------------------
| Student Routes (Student Panel)
|--------------------------------------------------------------------------
|
*/

// Student Panel Routes
Route::prefix('student')->group(function() {
  // Auth
  Route::get('/login', 'Auth\StudentLoginController@showLoginForm')->name('student.login');
  Route::post('/login', 'Auth\StudentLoginController@login')->name('student.login.submit');
  Route::get('/logout', 'Auth\StudentLoginController@logout');
  Route::get('/', 'StudentController@index')->name('student');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Teacher extends Authenticatable
{
    use Notifiable;

    protected $guard = 'teacher';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function students() {
      return $this->hasMany('App\Student');
    }

    public function school() {
      return $this->belongsTo('App\School');
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use Hash;
use App\School;
use App\Teacher;
use App\Student;
use Illuminate\Http\Request;
use App\Http\Requests\StoreTeacher;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Response;
use Illuminate\Contracts\Validation\Validator;

class TeacherController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin', ['except' => 'logout']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $teachers = Teacher::all();
      $schools = School::all();
      return view('admin.teachers.index')
                    ->with('teachers', $teachers)
                    ->with('schools', $schools);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTeacher $request)
    {
        $filename = $request->file('media')->getClientOriginalName();
        $teacherName = $request->input('name');
        $file = $request->file('media')->storeAs('public/teachers/'.$teacherName, $filename);

        // Path where files are stored according to Filesystem.php
        $path = storage_path('app/public/teachers/'.$teacherName);

        // Edit files
        $img_square = Image::make($path.'/'.$filename)->fit(500)->save();

        $teacher = new Teacher;
        $teacher->name = $request->input('name');
        $teacher->email = $request->input('email');
        $teacher->profile_img = $file;
        $teacher->password = Hash::make($request->input('password'));
        $teacher->students_slots = $request->input('students_slots');
        $teacher->school_id = $request->input('school_id');

        $teacher->save();

        $request->session()->flash('success', 'New teacher created!');
        return redirect('admin/teachers');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $teacher = Teacher::findOrFail($id);
      $students = Student::where('teacher_id', '=', $id)->get();
      $students_num = count($students);
      return view('admin.teachers.show')
                  ->with('teacher', $teacher)
                  ->with('students', $students)
                  ->with('students_num', $students_num);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $schools = School::all();
      $teacher = Teacher::findOrFail($id);
      return view('admin.teachers.edit')
                  ->with('teacher', $teacher)
                  ->with('schools', $schools);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, array(
        'name' => 'required',
        'email' => 'required',
        'password' => 'required',
        'school_id' => 'required',
      ));

      $teacher = Teacher::findOrFail($id);

      // If image has changed
      if ($request->file('media')) {
        $file = $teacher->profile_img;
        Storage::delete($file);
        $filename = $request->file('media')->getClientOriginalName();
        $teacherName = $request->input('name');
        $file = $request->file('media')->storeAs('public/teachers/'.$teacherName, $filename);
        $path = storage_path('app/public/teachers/'.$teacherName);
        $img_square = Image::make($path.'/'.$filename)->fit(500)->save();
        $teacher->profile_img = $file;
      }
      $teacher->status = $request->input('status');
      $teacher->name = $request->input('name');
      $teacher->email = $request->input('email');
      $teacher->password = Hash::make($request->input('password'));
      $teacher->students_slots = $request->input('students_slots');
      $teacher->school_id = $request->input('school_id');
      $teacher->save();

      $request->session()->flash('success', 'Teacher updated!');
      $redirect = 'admin/teachers/'.$teacher->id;
      return redirect()->route('teachers.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $teacher = Teacher::findOrFail($id);
      $file = $teacher->profile_img;
      Storage::delete($file);
      $teacher->delete();
      session()->flash('success', 'Teacher Deleted!');
      return redirect('/admin/teachers');
    }

    public function storeStudent(Request $request, $id)
    {
      $teacher = Teacher::findOrFail($id);
      $this->validate($request, array(
        'name' => 'required',
        'email' => 'required',
        'password' => 'required'
      ));
      $student = new Student;
      $student->name = $request->input('name');
      $student->email = $request->input('email');
      $student->password = $request->input('password');
      $student->teacher_id = $teacher->id;
      $student->school_id = $teacher->school_id;
      $student->save();
      $request->session()->flash('success', 'New student created!');
      return redirect()->route('teachers.show', $id);
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
     {
         $this->middleware('auth:teacher', ['except' => 'logout']);
     }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        $teacher = Teacher::find($id);
        return view('teacher')->with('teacher', $teacher);
    }
}

resources/views/layouts/teacher/_footer.blade.php
<div class="copyright text-center mt-5">
  © Copyright 2017 Simone Pozzobon
</div>

resources/views/layouts/teacher/_head.blade.php
<head>
  <meta charset="utf-8">
  <meta name="description" content="Admin Template">
  <meta name="author" content="Simone Pozzobon">

  <title>Admin Panel - @yield('title')</title>

  {{-- Main Stylesheet --}}
  <link rel="stylesheet" href="{{ asset('css/app.css') }}">
  {{-- Image Picker --}}
  <link rel="stylesheet" href="{{ asset('admin-assets/css/image-picker.css') }}">
  {{-- Custom Style --}}
  <link rel="stylesheet" href="{{ asset('admin-assets/css/style.css') }}">

  {{-- Google Analytics --}}
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-92981271-1', 'auto');
  ga('send', 'pageview');

</script>

  @yield('stylesheets')

</head>

resources/views/layouts/teacher/_menu.blade.php
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  {{-- Mobile --}}
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {{-- Logo --}}
  <a href="{{ url('/admin') }}" class="navbar-brand"><img src="/img/logo.png" height="50" style="max-width: 40vw;"></a>
  <div class="collapse navbar-collapse justify-content-start" id="">
    @if (Auth::guard('teacher')->check())
      <li class="nav-link">
        <a href="{{ url('/') }}" target="_blank">Visit Website</a>
      </li>
    @endif
  </div>
  {{-- Desktop --}}
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">

    @if (Auth::guard('teacher')->check())
      <li class="nav-link dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="nav-link"><a href="{{ route('admin.admins.index') }}">Admins</a></li>
          <li class="nav-link "><a href="{{ route('teachers.index') }}">Teachers</a></li>
          <li class="nav-link"><a href="{{ route('students.index') }}">Students</a></li>
          <li class="nav-link"><a href="{{ route('users.index') }}">Users</a></li>
          <div class="dropdown-divider"></div>
          <li class="nav-link"><a href="{{ route('schools.index') }}">Schools</a></li>
          <li class="nav-link"><a href="{{ route('partners.index') }}">Partners</a></li>
        </ul>
      </li>
      <li class="nav-link dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="nav-link">Edit Account<li>
          <div class="dropdown-divider"></div>
          <li class="nav-link"><a href="{{ url('teacher/logout') }}">Logout</a></li>
        </ul>
      </li>
    @endif

  </div>
</nav>

resources/views/layouts/teacher/_scripts.blade.php
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

{{-- Bootstrap --}}
<script src="{{ asset('admin-assets/js/image-picker.min.js') }}"></script>
<script src="{{ asset('admin-assets/js/custom.js') }}"></script>

@yield('scripts')