routes/web.php
<?php

use App\Post;
use App\Partner;

// use Symfony\Component\Debug\Debug;
// Debug::enable();

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/


/*
|--------------------------------------------------------------------------
| WORKING
|--------------------------------------------------------------------------
*/

Route::get('video-test', 'Admin\VideoController@index')->name('video-test.index');


/*
|--------------------------------------------------------------------------
| NEED UPDATE
|--------------------------------------------------------------------------
*/

// need to create a controller for these maybe Main or FrontendController
Route::get('/', function () {
    return view('new');
});

/*
|--------------------------------------------------------------------------
| DONE
|--------------------------------------------------------------------------
*/

// Auth
Auth::routes();
// Logout
Route::get('/logout', 'Auth\LoginController@logout');


/*
|
|
|--------------------------------------------------------------------------
| Admin Routes (Admin Panel)
|--------------------------------------------------------------------------
|
*/

// Admin Panel Routes
Route::prefix('admin')->group(function () {

  /*
  |--------------------------------------------------------------------------
  | WORKING
  |--------------------------------------------------------------------------
  | - add video library to manage all the video in once then assign to apps.
  */
  Route::prefix('/video-library')->group(function() {
    Route::resource('/video-api-library', 'Admin\VideoLibraryController');
    Route::get('/', function() {
      return view('admin.video_library.index');
    })->name('video-library.index');
  });

  /*
  |--------------------------------------------------------------------------
  | DONE
  |--------------------------------------------------------------------------
  */
  // Auth
  Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
  Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
  Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
  Route::get('/', 'AdminController@index')->name('admin');

  // Users menu routes
  Route::get('/admins', 'Admin\AdminController@index')->name('admin.admins.index');
  Route::resource('teachers', 'Admin\TeacherController', ['except' => ['create']]);
  Route::post('teachers/{teacher}', 'Admin\TeacherController@storeStudent')->name('teacher.store.student');
  Route::resource('students', 'Admin\StudentController', ['except' => ['create']]);
  Route::resource('users', 'Admin\UserController', ['except' => ['create']]);
  Route::resource('schools', 'Admin\SchoolController', ['except' => ['create']]);

  // Settings menu routes
  Route::resource('partners', 'Admin\PartnerController', ['except' => ['create'] ]);

});


/*
|
|
|--------------------------------------------------------------------------
| Teacher Routes (Teacher Panel)
|--------------------------------------------------------------------------
|
*/

// Teacher Panel Teacher
Route::prefix('teacher')->group(function() {
  // Auth
  Route::get('/login', 'Auth\TeacherLoginController@showLoginForm')->name('teacher.login');
  Route::post('/login', 'Auth\TeacherLoginController@login')->name('teacher.login.submit');
  Route::get('/logout', 'Auth\TeacherLoginController@logout')->name('teacher.logout');
  Route::get('/', 'TeacherController@index')->name('teacher');

  // Apps
  Route::get('/app', 'AppController@firstApp')->name('app.first');
});


/*
|
|
|--------------------------------------------------------------------------
| Student Routes (Student Panel)
|--------------------------------------------------------------------------
|
*/

// Student Panel Routes
Route::prefix('student')->group(function() {
  // Auth
  Route::get('/login', 'Auth\StudentLoginController@showLoginForm')->name('student.login');
  Route::post('/login', 'Auth\StudentLoginController@login')->name('student.login.submit');
  Route::get('/logout', 'Auth\StudentLoginController@logout');
  Route::get('/', 'StudentController@index')->name('student');
});

app/VideoLibrary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VideoLibrary extends Model
{
    protected $table = 'video_libraries';
}

app/Http/Controllers/Admin/VideoLibraryController.php
<?php

namespace App\Http\Controllers\Admin;

use FFMpeg;
use App\VideoLibrary;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class VideoLibraryController extends Controller
{
    public function index()
    {
        $videos = VideoLibrary::all();
        return response(compact('videos'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
      $bins = [
          'ffmpeg.binaries'  => '/usr/local/bin/ffmpeg', // the path to the FFMpeg binary
          'ffprobe.binaries' => '/usr/local/bin/ffprobe', // the path to the FFProbe binary
      ];

        session()->flash('success',$request);

        // // Init FFmpeg
        // $ffmpeg = FFMpeg\FFMpeg::create($bins);
        //
        // // get the file
        // $file = $request->file('video');
        // $fileExt = $file->getClientOriginalExtension();
        // $filename = uniqid();
        //
        // // salvo il file così com'è
        // $file = $file->storeAs('public/video', "$filename.$fileExt");
        //
        // // Set the absolute path to storage folder
        // $globalPath = Storage::disk('local')->getDriver()->getAdapter();
        //
        // // Creo l'oggetto video
        // $filePath = $globalPath->applyPathPrefix($file);
        // $video = $ffmpeg->open($filePath);
        //
        // // Prendo la durata del video
        // $ffprobe = FFMpeg\FFProbe::create($bins);
        // $length = $ffprobe
        //     ->format($filePath) // extracts file informations
        //     ->get('duration');
        //
        // // Definisco il percorso per per il frame
        // $thumbPath = $globalPath->applyPathPrefix("public/video/$filename.jpg");
        //
        // // Estraggo il frame
        // if ($length > 10) {
        //   $thumb = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))->save($thumbPath);
        // } else {
        //   $middle = $length / 2;
        //   $thumb = $video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds($middle))->save($thumbPath);
        // }
        //
        // //scrivo la path pubblica senza esporre le cartelle del server
        // $thumbPublic = Storage::url("video/$filename.jpg");
        //
        // // Converto il video nel formato mp4
        // $format = new FFMpeg\Format\Video\X264('aac', 'libx264');
        //
        // // Da lavorare, deve mandarmi indietro il progress di quello che sta succedendo
        // $format->on('progress', function ($video, $format, $percentage) {
        //   session()->flash('info', "$percentage % transcoded");
        // });
        //
        // // Setto i parametri aggiuntivi per la conversione
        // $format->getExtraParams();
        // $format->setAudioChannels(2)->setAudioKiloBitrate(256);
        //
        // // Setto il formato unico per i video 1920x1080
        // $video->filters()
        //       ->pad(new FFMpeg\Coordinate\Dimension(1920, 1080));
        //
        // // Salvo il file
        // $videoPath = $globalPath->applyPathPrefix("public/video/$filename.mp4");
        // $video->save($format, $videoPath);
        // $videoPublic = Storage::url("video/$filename.mp4");
        //
        // // se il file non è un mp4 allora elimino la versione originale lasciando solo quella convertita
        // if ($fileExt != 'mp4') {
        //   Storage::delete($file);
        // }
        //
        // // Salvo nel DB
        // $video = new VideoLibrary;
        // $video->title = $request->input('title');
        // $video->path_x264 = $videoPublic;
        // $video->thumb = $thumbPublic;
        // $video->save();
        //
        // $request->session()->flash('success', 'Video uploaded!');
        //
        // return response()->json(['success' => true]);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        $video = VideoLibrary::find($id);
        Storage::delete($video->path);
        Storage::delete($video->thumb);
        $video->delete();

        $request->session()->flash('success', 'Video Deleted!');
        return redirect('admin/video-library');

    }
}

resources/views/admin/video_library/index.blade.php
@extends('layouts.admin')
@section('title')
  Video Library
@endsection
@section('page-title')
  Video Library
@endsection
@section('stylesheets')
  <meta name="csrf-token" content="{{ csrf_token() }}">
  {{-- JQuery --}}
  <script src="{{ asset('/js/jquery-3.2.0.min.js') }}">

  </script>
  {{-- Angular --}}
  <script src="{{ asset('/js/dev-libraries/angular.js') }}"></script>
  <script src="{{ asset('/js/dev-libraries/angular-animate.js') }}"></script>
  <script src="{{ asset('/js/dev-libraries/angular-aria.js') }}"></script>
  <script src="{{ asset('/js/dev-libraries/angular-messages.js') }}"></script>
@endsection
@section('content')
  <div class="clearfix" ng-app="videoLibraryApp" ng-controller="mainController" ng-cloak>
    <div class="row">
      <div class="col-md-8">
        <div class="container-fluid bg-faded p-4">
          <table class="table table-hover">
            <thead>
              <th>Id</th>
              <th>Title</th>
              <th>Preview</th>
              <th>Tools</th>
            </thead>
            <tbody>
                <tr ng-repeat="video in videos">
                  <td class="align-middle">@{{ video.id }}</td>
                  <td class="align-middle">@{{ video.title }}</td>
                  <td class="align-middle">
                    @{{ video.thumb }}
                    {{-- <img src="@{{ $video.thumb }}" width="57"> --}}
                  </td>
                  <td class="align-middle">
                    <div class="btn-group">
                      <a href="#" class="btn btn-info">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
                      </a>
                      <a href="#" class="btn btn-danger">
                        <i class="fa fa-trash" aria-hidden="true"></i> Delete
                      </a>
                    </div>
                  </td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-4">
        <div class="container-fluid bg-faded p-4">
          <h3>Add Video</h3>
          <hr>
          <form ng-submit="submitVideo()" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="form-group">
              <h5>Title</h5>
              <input type="text" name="title" class="form-control" ng-model="videoData.title">
            </div>
            <div class="form-group border-0">
              <h5>Video</h5>
              {{-- <input type="file" name="video" class="form-control" onchange="$scope.getFile(this)"> --}}
              <input type="file" data-file="param.file"/>
              <div>param.file: @{{param.file}}</div>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@section('scripts')
  <script type="text/javascript">
  // Define the service
    angular.module('videoService', [])
            .factory('Video', function($http, CSRF_TOKEN){
              // Get all the category
              return {
                get : function() {
                  return $http.get('{{ route('video-api-library.index') }}');
                },

                save : function(videoData) {
                  console.log('cosa sto salvando '+ $.param(videoData));
                    return $http({
                      method: 'POST',
                      url: '{{ route('video-api-library.store') }}',
                      data: $.param(videoData),
                      headers: {'Content-Type': 'multipart/form-data'}
                    });
                },

                update : function(videoData, id) {
                  console.log($.param(videoData));
                    return $http({
                      method: 'PUT',
                      url: '{{ route('video-api-library.index') }}/'+id,
                      data: $.param(videoData),
                      headers: {'Content-Type': 'multipart/form-data'}
                    });
                },

                destroy : function(id) {
                    return $http({
                      method: 'DELETE',
                      url: '{{ route('video-api-library.index') }}/'+id
                    });
                }
              }
            });

    // Define the controller
    angular.module('mainCtrl', [])
            .controller('mainController', function($scope, $http, Video) {
              // models
              $scope.videoData = {} // Initialize the object
              // Sorting Table
              $scope.sortType     = 'id'; // set the default sort type
              $scope.sortReverse  = false;

              // get function from factory of the Video service
              Video.get().then(function(response) {
                  $scope.videos = response.data.videos;
                  console.log($scope.videos);
                });

              $scope.getFile = function(element) {
                console.log(element);
              };

              $scope.submitVideo = function() {
                $scope.videoData.video = $scope.param.file;
                Video.save($scope.videoData)
                        .then(function successCallback(response) {
                          Video.get().then(function(response) {
                            $scope.videos = response.data.videos;
                          });
                        }, function errorCallback(response) {
                          console.log('errors '+response);
                        });
              };

            });

    // Define the Application
    var videoLibraryApp =
    angular.module('videoLibraryApp', [
              'mainCtrl',
              'videoService',
            ])
            .constant("CSRF_TOKEN", '{{ csrf_token() }}');

    videoLibraryApp.directive('file', function(){
                return {
                    scope: {
                        file: '='
                    },
                    link: function(scope, el, attrs){
                        el.bind('change', function(event){
                            var files = event.target.files;
                            var file = files[0];
                            scope.file = file ? file.name : undefined;
                            scope.$apply();
                        });
                    }
                };
            });
  </script>
@endsection